name: Keep Alive
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to signflix.onrender.com
        run: curl -s https://signflix.onrender.com > /dev/null
