name: Build and deploy Node.js app to Azure Web App - SignFlix-redirect

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: ./site1
        run: npm ci

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: express-app
          path: |
            site1/index.js
            site1/node_modules
            site1/package.json
            site1/package-lock.json

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: express-app
          path: ./site1

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8941D766BCE84825844B46ED61CD1C8F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AA7927BF96594048B5D5822F288DCAC7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E589918573C74750807A66DC4495361F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'SignFlix-prod'
          slot-name: 'Production'
          package: ./site1
